@startuml
left to right direction
skinparam packageStyle rectangle

actor "Solicitante" as Solicitante
actor "Responsable de Sistemas" as Sistemas
actor "Especialista Externo" as Externo

rectangle "Sistema de gestión de incidencias\nLogística y Minería S.A." {
  usecase "CU-01\nRegistrar incidencia" as CU01
  usecase "Adjuntar archivo" as Adjuntar

  usecase "CU-02\nConsultar incidencias propias" as CU02
  usecase "CU-03\nConsultar incidencias registradas" as CU03
  usecase "CU-04\nAsignar prioridad" as CU04
  usecase "CU-06\nAsignar o reasignar responsable" as CU06
  usecase "CU-07\nGestionar especialistas externos" as CU07
  usecase "CU-10\nConsultar historial" as CU10

  usecase "CU-05 / CU-11\nActualizar estado" as CU05
  usecase "CU-08\nConsultar incidencias asignadas" as CU08
  usecase "CU-09 / CU-12\nRegistrar seguimiento" as CU09
  usecase "Registrar resolución final\ny cerrar incidencia" as Cerrar
  usecase "CU-13\nInformar imposibilidad de atender una incidencia" as CU13

  usecase "Notificar al Solicitante" as Notificar
}

Solicitante -- CU01
Solicitante -- CU02

Sistemas -- CU03
Sistemas -- CU04
Sistemas -- CU05
Sistemas -- CU06
Sistemas -- CU07
Sistemas -- CU09
Sistemas -- CU10
Sistemas -- Cerrar
Sistemas -- CU13

Externo -- CU05
Externo -- CU08
Externo -- CU09
Externo -- CU13

Adjuntar ..> CU01 : <<extend>>

CU05 ..> Notificar : <<include>>
CU06 ..> Notificar : <<include>>
Cerrar ..> Notificar : <<include>>
Cerrar ..> CU09 : <<extend>>

@enduml
